### Pandas para Manipulación de Datos

**Pandas** es una librería poderosa y flexible de Python que se utiliza principalmente para manipulación, análisis y limpieza de datos. Proporciona dos estructuras de datos principales: **Series** (para datos unidimensionales) y **DataFrames** (para datos bidimensionales), que permiten trabajar con conjuntos de datos de manera eficiente.

A continuación, te explico las principales funcionalidades de Pandas para la manipulación de datos:

---

### 1. **Creación de DataFrames**

Un **DataFrame** es la estructura principal en Pandas. Es una tabla bidimensional con columnas etiquetadas de diferentes tipos (numéricas, de texto, etc.). Puedes crear DataFrames de varias maneras.

Un DataFrame en pandas es una estructura de datos bidimensional, similar a una tabla, que permite almacenar y manipular datos en filas y columnas, facilitando el análisis y manejo de grandes volúmenes de información en Python

Base de datos

* https://archive.ics.uci.edu/
* https://www.kaggle.com/datasets/tunguz/online-retail

In [2]:
import pandas as pd
path = '/content/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin1')
print(retail_data)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER       6.0
1        536365     71053                  WHITE METAL LANTERN       6.0
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER       8.0
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       6.0
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.       6.0
...         ...       ...                                  ...       ...
12909    537400     22429           ENAMEL MEASURING JUG CREAM       3.0
12910    537400     22771  CLEAR DRAWER KNOB ACRYLIC EDWARDIAN      12.0
12911    537400     22758     LARGE PURPLE BABUSHKA NOTEBOOK         2.0
12912    537400     22756      LARGE YELLOW BABUSHKA NOTEBOOK        2.0
12913    537400     22757                                  LAR       NaN

         InvoiceDate  UnitPrice  CustomerID         Country
0       12/1/10 8:26       2.55     17850.0  United Kingdom
1       12/1/10 8:26       3.39     17850.0  United Kingdom
2       12/1/10 8:26       2.75     17850.0  United Kingdom
3       12/1/10 8:26       3.39     17850.0  United Kingdom
4       12/1/10 8:26       3.39     17850.0  United Kingdom
...              ...        ...         ...             ...
12909  12/6/10 14:36       4.25     17191.0  United Kingdom
12910  12/6/10 14:36       1.25     17191.0  United Kingdom
12911  12/6/10 14:36       1.25     17191.0  United Kingdom
12912  12/6/10 14:36       1.25     17191.0  United Kingdom
12913            NaN        NaN         NaN             NaN

[12914 rows x 8 columns]

In [ ]:
print(retail_data.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

## Creacion de dataframe

In [3]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_from_array = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df_from_array)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
data = [[1,'jhon',22], [14,'Anna',33]]
df_from_array = pd.DataFrame(data, columns=['id','name','age'])
print(df_from_array)

   id  name  age
0   1  jhon   22
1  14  Anna   33

In [ ]:
data = [{'ID':1, 'Name':'Jhon', 'Age':22}, {'ID':14, 'Name':'Anna', 'Age':33}]
df_from_array = pd.DataFrame(data)
print(df_from_array)

   ID  Name  Age
0   1  Jhon   22
1  14  Anna   33

In [ ]:
data = {'ID': [1,2,3], 'name':['jhon','anna','mike'], 'age':[22,24,25]}
df_from_array = pd.DataFrame(data)
print(df_from_array)

   ID  name  age
0   1  jhon   22
1   2  anna   24
2   3  mike   25

## Series

es una estructura de datos unidimensional, similar a una lista o array de una sola columna. Cada elemento en una Serie tiene un índice asociado, que por defecto es un número entero, pero puede personalizarse. Podrías pensarlo como una columna de un DataFrame

In [ ]:
data = {'ID': pd.Series([1,2,3]), 'name':pd.Series(['jhon','anna','mike']), 'age':pd.Series([22,24,25])}
df_from_array = pd.DataFrame(data)
print(df_from_array)

   ID  name  age
0   1  jhon   22
1   2  anna   24
2   3  mike   25

In [ ]:
# Nombres de columnas
columnas_names = retail_data. columns
print(columnas_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [ ]:
num_rows, num_columns = retail_data.shape
print(f"Número de filas: {num_rows}")
print(f"Número de columnas: {num_columns}")

Número de filas: 541909
Número de columnas: 8

In [ ]:
#Uso de describe() para obtener un resumen estadístico.
# Resumen estadístico
summary = retail_data.describe()
print("Resumen estadístico:\\n", summary)

#Cálculo de la media y mediana.
#Media:
mean_value = retail_data['Quantity'].mean()
print("Media de Quantity:", mean_value)

#Mediana:
median_value = retail_data['Quantity'].median()
print("Mediana de Quantity:", median_value)

#Suma y conteo de valores.
#Suma:
total_sum = retail_data['Quantity'].sum()
print("Suma de Quantity:", total_sum)

#Conteo de valores:
count_values = retail_data['Quantity'].count()
print("Conteo de Quantity:", count_values)

#Desviación estándar y varianza.
#Desviación estándar:
std_dev = retail_data['Quantity'].std()
print("Desviación estándar de Quantity:", std_dev)

#Varianza
variance = retail_data['Quantity'].var()
print("Varianza de Quantity:", variance)

#Mínimo, Máximo y Producto.
#Mínimo:
min_value = retail_data['Quantity'].min()
print("Mínimo de Quantity:", min_value)

#Máximo:
max_value = retail_data['Quantity'].max()
print("Máximo de Quantity:", max_value)

#Producto:
prod_value = retail_data['Quantity'].prod()
print("Producto de Quantity:", prod_value)

Resumen estadístico:\n             Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000
Media de Quantity: 9.55224954743324
Mediana de Quantity: 3.0
Suma de Quantity: 5176450
Conteo de Quantity: 541909
Desviación estándar de Quantity: 218.08115784986612
Varianza de Quantity: 47559.39140913822
Mínimo de Quantity: -80995
Máximo de Quantity: 80995
Producto de Quantity: 0

In [ ]:
daily_sales = pd.Series([10,20,None, 40,50])
total_sum = daily_sales.sum()
print(total_sum)

count_values = daily_sales.count()
print(count_values)

120.0
4

## iloc y loc

In [ ]:
first_row = retail_data.iloc[0]
print(first_row)

In [ ]:
first_five_rows = retail_data.iloc[6:8]
print(first_five_rows)

  InvoiceNo StockCode                        Description  Quantity  \
6    536365     21730  GLASS STAR FROSTED T-LIGHT HOLDER         6
7    536366     22633             HAND WARMER UNION JACK         6

    InvoiceDate  UnitPrice  CustomerID         Country
6  12/1/10 8:26       4.25     17850.0  United Kingdom
7  12/1/10 8:28       1.85     17850.0  United Kingdom

In [ ]:
subset = retail_data.iloc[2:5, 1:3]
print(subset)

  StockCode                          Description
2    84406B       CREAM CUPID HEARTS COAT HANGER
3    84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4    84029E       RED WOOLLY HOTTIE WHITE HEART.

In [ ]:
retail_value = retail_data.iloc[1,3]
print(retail_value)

6

In [ ]:
row_index_3 = retail_data.loc[3]
print(row_index_3)

InvoiceNo                                   536365
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         6
InvoiceDate                           12/1/10 8:26
UnitPrice                                     3.39
CustomerID                                 17850.0
Country                             United Kingdom
Name: 3, dtype: object

In [ ]:
row_index_0_to_4 = retail_data.loc[0:4]
print(row_index_0_to_4)

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [ ]:
quantity_column = retail_data.loc[:, 'Quantity']
print(quantity_column)

0         6
1         6
2         8
3         6
4         6
         ..
77895    12
77896     2
77897    20
77898     1
77899     4
Name: Quantity, Length: 77900, dtype: int64

In [ ]:
#consultar mas de una columna
quantity_unitprices_column = retail_data.loc[:, ['Quantity','UnitPrice']]
print(quantity_column)

0         6
1         6
2         8
3         6
4         6
         ..
77895    12
77896     2
77897    20
77898     1
77899     4
Name: Quantity, Length: 77900, dtype: int64

# Datos faltantes

Estan formados por nan

In [ ]:
missing_values = retail_data.isnull()
print(missing_values)

       InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0          False      False        False     False        False      False
1          False      False        False     False        False      False
2          False      False        False     False        False      False
3          False      False        False     False        False      False
4          False      False        False     False        False      False
...          ...        ...          ...       ...          ...        ...
77895      False      False        False     False        False      False
77896      False      False        False     False        False      False
77897      False      False        False     False        False      False
77898      False      False        False     False        False      False
77899      False      False        False     False        False      False

       CustomerID  Country
0           False    False
1           False    False
2           False    False
3           False    False
4           False    False
...           ...      ...
77895       False    False
77896       False    False
77897       False    False
77898       False    False
77899       False     True

[77900 rows x 8 columns]

In [ ]:
print(missing_values.head())

   InvoiceNo  StockCode  Description  Quantity  InvoiceDate  UnitPrice  \
0      False      False        False     False        False      False
1      False      False        False     False        False      False
2      False      False        False     False        False      False
3      False      False        False     False        False      False
4      False      False        False     False        False      False

   CustomerID  Country
0       False    False
1       False    False
2       False    False
3       False    False
4       False    False

Datos faltantes

In [ ]:
missing_data_count = retail_data.isna().sum()
print(missing_data_count)

InvoiceNo          0
StockCode          0
Description      241
Quantity           0
InvoiceDate        0
UnitPrice          0
CustomerID     28868
Country            1
dtype: int64

eliminar las partes faltantes para filas

In [ ]:
no_missing_rows = retail_data.dropna()
print(no_missing_rows)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
77894    542791     22624                 IVORY KITCHEN SCALES        12
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77896    542791     22064           PINK DOUGHNUT TRINKET POT          2
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20
77898    542791     22374      AIRLINE BAG VINTAGE JET SET RED         1

        InvoiceDate  UnitPrice  CustomerID         Country
0      12/1/10 8:26       2.55     17850.0  United Kingdom
1      12/1/10 8:26       3.39     17850.0  United Kingdom
2      12/1/10 8:26       2.75     17850.0  United Kingdom
3      12/1/10 8:26       3.39     17850.0  United Kingdom
4      12/1/10 8:26       3.39     17850.0  United Kingdom
...             ...        ...         ...             ...
77894  2/1/11 10:47       7.65     15039.0  United Kingdom
77895  2/1/11 10:47       1.25     15039.0  United Kingdom
77896  2/1/11 10:47       1.65     15039.0  United Kingdom
77897  2/1/11 10:47       1.95     15039.0  United Kingdom
77898  2/1/11 10:47       4.25     15039.0  United Kingdom

[49031 rows x 8 columns]

eliminar las columnas con datos faltantes

In [ ]:
no_missing_columns = retail_data.dropna(axis=1)
print(no_missing_columns)

      InvoiceNo StockCode  Quantity   InvoiceDate  UnitPrice
0        536365    85123A         6  12/1/10 8:26       2.55
1        536365     71053         6  12/1/10 8:26       3.39
2        536365    84406B         8  12/1/10 8:26       2.75
3        536365    84029G         6  12/1/10 8:26       3.39
4        536365    84029E         6  12/1/10 8:26       3.39
...         ...       ...       ...           ...        ...
77895    542791     22775        12  2/1/11 10:47       1.25
77896    542791     22064         2  2/1/11 10:47       1.65
77897    542791    85099B        20  2/1/11 10:47       1.95
77898    542791     22374         1  2/1/11 10:47       4.25
77899    542791     22219         4  2/1/11 10:47       0.85

[77900 rows x 5 columns]

In [ ]:
retail_data_filled_zeros = retail_data.fillna(0)
print(retail_data_filled_zeros)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77896    542791     22064           PINK DOUGHNUT TRINKET POT          2
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20
77898    542791     22374      AIRLINE BAG VINTAGE JET SET RED         1
77899    542791     22219   LOVEBIRD HANGING DECORATION WHITE          4

        InvoiceDate  UnitPrice  CustomerID         Country
0      12/1/10 8:26       2.55     17850.0  United Kingdom
1      12/1/10 8:26       3.39     17850.0  United Kingdom
2      12/1/10 8:26       2.75     17850.0  United Kingdom
3      12/1/10 8:26       3.39     17850.0  United Kingdom
4      12/1/10 8:26       3.39     17850.0  United Kingdom
...             ...        ...         ...             ...
77895  2/1/11 10:47       1.25     15039.0  United Kingdom
77896  2/1/11 10:47       1.65     15039.0  United Kingdom
77897  2/1/11 10:47       1.95     15039.0  United Kingdom
77898  2/1/11 10:47       4.25     15039.0  United Kingdom
77899  2/1/11 10:47       0.85     15039.0               0

[77900 rows x 8 columns]

La cantidad de datos vacios despues de llenar con zeros

In [ ]:
retail_data_filled_zeros = retail_data.fillna(0)
missing_data_count = retail_data_filled_zeros.isna().sum()
print(missing_data_count)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Muestra en la consola el DataFrame retail_data_filled_mean, donde los valores NaN han sido sustituidos por la media de UnitPrice.

In [ ]:
mean_unit_price = retail_data['UnitPrice'].mean()
retail_data_filled_mean = retail_data.fillna(mean_unit_price)
print(retail_data_filled_mean)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77896    542791     22064           PINK DOUGHNUT TRINKET POT          2
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20
77898    542791     22374      AIRLINE BAG VINTAGE JET SET RED         1
77899    542791     22219   LOVEBIRD HANGING DECORATION WHITE          4

        InvoiceDate  UnitPrice  CustomerID         Country
0      12/1/10 8:26       2.55     17850.0  United Kingdom
1      12/1/10 8:26       3.39     17850.0  United Kingdom
2      12/1/10 8:26       2.75     17850.0  United Kingdom
3      12/1/10 8:26       3.39     17850.0  United Kingdom
4      12/1/10 8:26       3.39     17850.0  United Kingdom
...             ...        ...         ...             ...
77895  2/1/11 10:47       1.25     15039.0  United Kingdom
77896  2/1/11 10:47       1.65     15039.0  United Kingdom
77897  2/1/11 10:47       1.95     15039.0  United Kingdom
77898  2/1/11 10:47       4.25     15039.0  United Kingdom
77899  2/1/11 10:47       0.85     15039.0        5.572745

[77900 rows x 8 columns]

## Creación y Manipulación de Columnas en Pandas

In [ ]:
retail_data['TotalPrice'] = retail_data['Quantity'] * retail_data['UnitPrice']
print(retail_data.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice
0  12/1/10 8:26       2.55     17850.0  United Kingdom       15.30
1  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
2  12/1/10 8:26       2.75     17850.0  United Kingdom       22.00
3  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34
4  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34

In [ ]:
retail_data['HighValue']=retail_data['TotalPrice']>16 #.apply(lambda x: 1 if x > 100 else 0)
print(retail_data['HighValue'].head(10))

0    False
1     True
2     True
3     True
4     True
5    False
6     True
7    False
8    False
9     True
Name: HighValue, dtype: bool

In [ ]:
print(retail_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77900 entries, 0 to 77899
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    77900 non-null  object
 1   StockCode    77900 non-null  object
 2   Description  77659 non-null  object
 3   Quantity     77900 non-null  int64
 4   InvoiceDate  77900 non-null  object
 5   UnitPrice    77900 non-null  float64
 6   CustomerID   49032 non-null  float64
 7   Country      77899 non-null  object
 8   TotalPrice   77900 non-null  float64
 9   HighValue    77900 non-null  bool
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 5.4+ MB
None

Cambiar el tipo de dato para cada campo de cada registro

In [4]:
retail_data['InvoiceDate'] = pd.to_datetime(retail_data['InvoiceDate'])
print(retail_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12914 entries, 0 to 12913
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    12914 non-null  object
 1   StockCode    12914 non-null  object
 2   Description  12869 non-null  object
 3   Quantity     12913 non-null  float64
 4   InvoiceDate  12913 non-null  datetime64[ns]
 5   UnitPrice    12913 non-null  float64
 6   CustomerID   9408 non-null   float64
 7   Country      12913 non-null  object
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 807.3+ KB
None

<ipython-input-4-c4c4f987284d>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  retail_data['InvoiceDate'] = pd.to_datetime(retail_data['InvoiceDate'])

In [ ]:
retail_data['DiscountedPrice'] = retail_data['UnitPrice'].apply(lambda x: x * 0.9)
print(retail_data.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice
0      False            2.295
1       True            3.051
2       True            2.475

Categorizar precios

In [ ]:
def categorize_price(price):
  if price >50:
    return 'High'
  elif price <20:
    return 'Medium'
  else:
    return 'Low'

retail_data['PriceCategory'] = retail_data['UnitPrice'].apply(categorize_price)
print(retail_data.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00

   HighValue  DiscountedPrice PriceCategory
0      False            2.295        Medium
1       True            3.051        Medium
2       True            2.475        Medium


## Agrupaciones con groupby

In [ ]:
country_count = retail_data['Country'].value_counts()
print(country_count)

Country
United Kingdom     72238
Germany             1404
France              1114
EIRE                 637
Spain                460
Netherlands          301
Portugal             242
Switzerland          209
Australia            162
Belgium              158
Italy                155
Norway               147
Cyprus                99
Japan                 69
Sweden                62
Iceland               60
Hong Kong             57
Singapore             56
Channel Islands       49
Lebanon               45
Lithuania             35
Poland                33
Greece                32
Finland               28
Denmark               20
Israel                16
Austria                9
Bahrain                2
Name: count, dtype: int64

contar la cantidad total de cada pais, usando groupby

In [ ]:
country_group = retail_data.groupby('Country')['Quantity'].sum()
print(country_count)

Country
United Kingdom     72238
Germany             1404
France              1114
EIRE                 637
Spain                460
Netherlands          301
Portugal             242
Switzerland          209
Australia            162
Belgium              158
Italy                155
Norway               147
Cyprus                99
Japan                 69
Sweden                62
Iceland               60
Hong Kong             57
Singapore             56
Channel Islands       49
Lebanon               45
Lithuania             35
Poland                33
Greece                32
Finland               28
Denmark               20
Israel                16
Austria                9
Bahrain                2
Name: count, dtype: int64

In [ ]:
country_stats = retail_data.groupby('Country')['UnitPrice'].agg(['sum', 'mean', 'max', 'min'])
print(country_stats)

                       sum      mean       max   min
Country
Australia           482.60  2.979012     12.75  0.36
Austria              65.12  7.235556     40.00  0.42
Bahrain               7.62  3.810000      3.81  3.81
Belgium             499.18  3.159367     18.00  0.12
Channel Islands     359.37  7.334082     50.00  0.42
Cyprus              490.69  4.956465    125.00  0.42
Denmark              92.97  4.648500     18.00  0.42
EIRE               2968.10  4.659498     65.00  0.00
Finland             146.25  5.223214     40.00  0.29
France             3911.35  3.511086    150.00  0.19
Germany            4977.88  3.545499     34.95  0.00
Greece              207.39  6.480937     14.95  1.25
Hong Kong           178.86  3.137895     12.75  0.21
Iceland             162.76  2.712667     12.75  0.42
Israel               68.00  4.250000      7.65  1.25
Italy               580.20  3.743226     35.00  0.42
Japan               131.35  1.903623      5.95  0.36
Lebanon             242.44  5.387556     14.95  0.55
Lithuania            99.44  2.841143      5.95  1.25
Netherlands         605.31  2.010997     15.00  0.21
Norway              238.83  1.624694      8.50  0.29
Poland              115.03  3.485758     12.75  0.42
Portugal            923.64  3.816694     28.00  0.21
Singapore           263.34  4.702500    125.00  0.21
Spain              4530.86  9.849696   1715.85  0.19
Sweden              196.64  3.171613     40.00  0.19
Switzerland         582.83  2.788660     40.00  0.18
United Kingdom   410987.97  5.689360  16888.02  0.00

para mas de una columna

In [ ]:
country_stock_group = retail_data.groupby(['Country', 'StockCode'])['Quantity'].sum()
print(country_stock_group)

Country         StockCode
Australia       20675           72
                20676           72
                20677           72
                20685           24
                20712           10
                                ..
United Kingdom  gift_0001_20     2
                gift_0001_30     1
                gift_0001_40     1
                gift_0001_50     1
                m                1
Name: Quantity, Length: 6605, dtype: int64

In [ ]:
# Calcular el top 3 de mejores países por ventas
top_countries = retail_data.groupby('Country')['Quantity'].sum().nlargest(3)
top_countries

Country
United Kingdom    540858
Netherlands        27228
Germany            15675
Name: Quantity, dtype: int64

In [ ]:
# Calcular el top 3 de peores países por ventas
worst_countries = retail_data.groupby('Country')['Quantity'].sum().nsmallest(3)
worst_countries

Country
Bahrain     0
Austria     3
Israel     44
Name: Quantity, dtype: int64

Filtrado de datos con condiciones en Pandas

Ventas que se realizaron es un pais

In [ ]:
uk_sales = retail_data[retail_data['Country'] == 'United Kingdom']
print(uk_sales)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
77894    542791     22624                 IVORY KITCHEN SCALES        12
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77896    542791     22064           PINK DOUGHNUT TRINKET POT          2
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20
77898    542791     22374      AIRLINE BAG VINTAGE JET SET RED         1

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
77894 2011-02-01 10:47:00       7.65     15039.0  United Kingdom       91.80
77895 2011-02-01 10:47:00       1.25     15039.0  United Kingdom       15.00
77896 2011-02-01 10:47:00       1.65     15039.0  United Kingdom        3.30
77897 2011-02-01 10:47:00       1.95     15039.0  United Kingdom       39.00
77898 2011-02-01 10:47:00       4.25     15039.0  United Kingdom        4.25

       HighValue  DiscountedPrice PriceCategory
0          False            2.295        Medium
1           True            3.051        Medium
2           True            2.475        Medium
3           True            3.051        Medium
4           True            3.051        Medium
...          ...              ...           ...
77894       True            6.885        Medium
77895      False            1.125        Medium
77896      False            1.485        Medium
77897       True            1.755        Medium
77898      False            3.825        Medium

[72238 rows x 12 columns]

In [ ]:
high_quantity_sales = retail_data[retail_data['Quantity'] > 10]
print(high_quantity_sales)

      InvoiceNo StockCode                          Description  Quantity  \
9        536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32
26       536370     22728            ALARM CLOCK BAKELIKE PINK        24
27       536370     22727            ALARM CLOCK BAKELIKE RED         24
28       536370     22726           ALARM CLOCK BAKELIKE GREEN        12
29       536370     21724      PANDA AND BUNNIES STICKER SHEET        12
...         ...       ...                                  ...       ...
77878    542790     21389       IVORY HANGING DECORATION  BIRD        12
77880    542790     21714         CITRONELLA CANDLE GARDEN POT        12
77894    542791     22624                 IVORY KITCHEN SCALES        12
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
9     2010-12-01 08:34:00       1.69     13047.0  United Kingdom       54.08
26    2010-12-01 08:45:00       3.75     12583.0          France       90.00
27    2010-12-01 08:45:00       3.75     12583.0          France       90.00
28    2010-12-01 08:45:00       3.75     12583.0          France       45.00
29    2010-12-01 08:45:00       0.85     12583.0          France       10.20
...                   ...        ...         ...             ...         ...
77878 2011-02-01 10:38:00       0.85     16612.0  United Kingdom       10.20
77880 2011-02-01 10:38:00       1.25     16612.0  United Kingdom       15.00
77894 2011-02-01 10:47:00       7.65     15039.0  United Kingdom       91.80
77895 2011-02-01 10:47:00       1.25     15039.0  United Kingdom       15.00
77897 2011-02-01 10:47:00       1.95     15039.0  United Kingdom       39.00

       HighValue  DiscountedPrice PriceCategory
9           True            1.521        Medium
26          True            3.375        Medium
27          True            3.375        Medium
28          True            3.375        Medium
29         False            0.765        Medium
...          ...              ...           ...
77878      False            0.765        Medium
77880      False            1.125        Medium
77894       True            6.885        Medium
77895      False            1.125        Medium
77897       True            1.755        Medium

[16006 rows x 12 columns]

In [ ]:
high_quantity_sales = retail_data[(retail_data['Quantity'] > 100) & (retail_data['Country'] == 'United Kingdom')]
print(high_quantity_sales)

      InvoiceNo StockCode                      Description  Quantity  \
96       536378     21212  PACK OF 72 RETROSPOT CAKE CASES       120
178      536387     79321                    CHILLI LIGHTS       192
179      536387     22780   LIGHT GARLAND BUTTERFILES PINK       192
180      536387     22779       WOODEN OWLS LIGHT GARLAND        192
181      536387     22466    FAIRY TALE COTTAGE NIGHTLIGHT       432
...         ...       ...                              ...       ...
77074    542694     15036        ASSORTED COLOURS SILK FAN       600
77078    542707     22492          MINI PAINT SET VINTAGE        108
77766    542785     16016      LARGE CHINESE STYLE SCISSOR       200
77768    542785     84992   72 SWEETHEART FAIRY CAKE CASES       120
77829    542789     84879    ASSORTED COLOUR BIRD ORNAMENT       160

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
96    2010-12-01 09:37:00       0.42     14688.0  United Kingdom       50.40
178   2010-12-01 09:58:00       3.82     16029.0  United Kingdom      733.44
179   2010-12-01 09:58:00       3.37     16029.0  United Kingdom      647.04
180   2010-12-01 09:58:00       3.37     16029.0  United Kingdom      647.04
181   2010-12-01 09:58:00       1.45     16029.0  United Kingdom      626.40
...                   ...        ...         ...             ...         ...
77074 2011-01-31 12:37:00       0.53     12908.0  United Kingdom      318.00
77078 2011-01-31 12:50:00       0.65     18095.0  United Kingdom       70.20
77766 2011-02-01 10:14:00       0.72     13881.0  United Kingdom      144.00
77768 2011-02-01 10:14:00       0.42     13881.0  United Kingdom       50.40
77829 2011-02-01 10:38:00       1.45     17511.0  United Kingdom      232.00

       HighValue  DiscountedPrice PriceCategory
96          True            0.378        Medium
178         True            3.438        Medium
179         True            3.033        Medium
180         True            3.033        Medium
181         True            1.305        Medium
...          ...              ...           ...
77074       True            0.477        Medium
77078       True            0.585        Medium
77766       True            0.648        Medium
77768       True            0.378        Medium
77829       True            1.305        Medium

[418 rows x 12 columns]

In [ ]:
sales_2011 = retail_data[retail_data['InvoiceDate'].dt.year == 2011]
print(sales_2011)

      InvoiceNo StockCode                          Description  Quantity  \
42481    539993     22386              JUMBO BAG PINK POLKADOT        10
42482    539993     21499                   BLUE POLKADOT WRAP        25
42483    539993     21498                  RED RETROSPOT WRAP         25
42484    539993     22379             RECYCLING BAG RETROSPOT          5
42485    539993     20718            RED RETROSPOT SHOPPER BAG        10
...         ...       ...                                  ...       ...
77895    542791     22775  PURPLE DRAWERKNOB ACRYLIC EDWARDIAN        12
77896    542791     22064           PINK DOUGHNUT TRINKET POT          2
77897    542791    85099B              JUMBO BAG RED RETROSPOT        20
77898    542791     22374      AIRLINE BAG VINTAGE JET SET RED         1
77899    542791     22219   LOVEBIRD HANGING DECORATION WHITE          4

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
42481 2011-01-04 10:00:00       1.95     13313.0  United Kingdom       19.50
42482 2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42483 2011-01-04 10:00:00       0.42     13313.0  United Kingdom       10.50
42484 2011-01-04 10:00:00       2.10     13313.0  United Kingdom       10.50
42485 2011-01-04 10:00:00       1.25     13313.0  United Kingdom       12.50
...                   ...        ...         ...             ...         ...
77895 2011-02-01 10:47:00       1.25     15039.0  United Kingdom       15.00
77896 2011-02-01 10:47:00       1.65     15039.0  United Kingdom        3.30
77897 2011-02-01 10:47:00       1.95     15039.0  United Kingdom       39.00
77898 2011-02-01 10:47:00       4.25     15039.0  United Kingdom        4.25
77899 2011-02-01 10:47:00       0.85     15039.0             NaN        3.40

       HighValue  DiscountedPrice PriceCategory
42481       True            1.755        Medium
42482      False            0.378        Medium
42483      False            0.378        Medium
42484      False            1.890        Medium
42485      False            1.125        Medium
...          ...              ...           ...
77895      False            1.125        Medium
77896      False            1.485        Medium
77897       True            1.755        Medium
77898      False            3.825        Medium
77899      False            0.765        Medium

[35419 rows x 12 columns]

In [ ]:
sales_2010 = retail_data[retail_data['InvoiceDate'].dt.year == 2010]
print(sales_2010)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
42476    539991     21618       4 WILDFLOWER BOTANICAL CANDLES         1
42477    539991     72741                GRAND CHOCOLATECANDLE         4
42478    539992     21470        FLOWER VINE RAFFIA FOOD COVER         1
42479    539992     22258              FELT FARM ANIMAL RABBIT         1
42480    539992     21155                RED RETROSPOT PEG BAG         1

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
42476 2010-12-23 16:49:00       1.25         NaN  United Kingdom        1.25
42477 2010-12-23 16:49:00       1.45         NaN  United Kingdom        5.80
42478 2010-12-23 17:41:00       3.75         NaN  United Kingdom        3.75
42479 2010-12-23 17:41:00       1.25         NaN  United Kingdom        1.25
42480 2010-12-23 17:41:00       2.10         NaN  United Kingdom        2.10

       HighValue  DiscountedPrice PriceCategory
0          False            2.295        Medium
1           True            3.051        Medium
2           True            2.475        Medium
3           True            3.051        Medium
4           True            3.051        Medium
...          ...              ...           ...
42476      False            1.125        Medium
42477      False            1.305        Medium
42478      False            3.375        Medium
42479      False            1.125        Medium
42480      False            1.890        Medium

[42481 rows x 12 columns]

In [ ]:
sales_dec_2010 = retail_data[(retail_data['InvoiceDate'].dt.year == 2010) & (retail_data['InvoiceDate'].dt.month == 12)]
print(sales_2010)

      InvoiceNo StockCode                          Description  Quantity  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1        536365     71053                  WHITE METAL LANTERN         6
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...         ...       ...                                  ...       ...
42476    539991     21618       4 WILDFLOWER BOTANICAL CANDLES         1
42477    539991     72741                GRAND CHOCOLATECANDLE         4
42478    539992     21470        FLOWER VINE RAFFIA FOOD COVER         1
42479    539992     22258              FELT FARM ANIMAL RABBIT         1
42480    539992     21155                RED RETROSPOT PEG BAG         1

              InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0     2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30
1     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
2     2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00
3     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
4     2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34
...                   ...        ...         ...             ...         ...
42476 2010-12-23 16:49:00       1.25         NaN  United Kingdom        1.25
42477 2010-12-23 16:49:00       1.45         NaN  United Kingdom        5.80
42478 2010-12-23 17:41:00       3.75         NaN  United Kingdom        3.75
42479 2010-12-23 17:41:00       1.25         NaN  United Kingdom        1.25
42480 2010-12-23 17:41:00       2.10         NaN  United Kingdom        2.10

       HighValue  DiscountedPrice PriceCategory
0          False            2.295        Medium
1           True            3.051        Medium
2           True            2.475        Medium
3           True            3.051        Medium
4           True            3.051        Medium
...          ...              ...           ...
42476      False            1.125        Medium
42477      False            1.305        Medium
42478      False            3.375        Medium
42479      False            1.125        Medium
42480      False            1.890        Medium

[42481 rows x 12 columns]

## Reestructuración de datos: Pivot y Reshape en Pandas


La función pd.pivot_table() en pandas permite transformar un DataFrame en una tabla dinámica, reorganizando los datos de manera más estructurada para facilitar el análisis.

In [ ]:
pivot_table = pd.pivot_table(retail_data, index='Country', columns='StockCode', values='Quantity', aggfunc='sum')
print(pivot_table)

StockCode        10002  10120  10123C  10124A  10124G  10125  10133   10135  \
Country
Australia          NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Austria            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Bahrain            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Belgium            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Channel Islands    NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Cyprus             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Denmark            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
EIRE              12.0    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Finland            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
France           252.0    NaN     NaN     NaN     NaN   20.0    NaN     NaN
Germany            1.0    NaN     NaN     NaN     NaN   40.0    NaN     NaN
Greece             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Hong Kong          NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Iceland            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Israel             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Italy              NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Japan              NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Lebanon            NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Lithuania          NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Netherlands        NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Norway             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Poland             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Portugal           NaN    NaN     NaN     NaN     NaN    NaN   20.0     NaN
Singapore          NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Spain             24.0    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Sweden             NaN    NaN     NaN     NaN     NaN    NaN    NaN     NaN
Switzerland       12.0    NaN     NaN     NaN     NaN    NaN    NaN     NaN
United Kingdom   290.0   16.0     1.0     4.0     5.0  307.0  290.0  1024.0

StockCode        11001  15034  ...  DCGS0076    DOT      M   POST    S  \
Country                        ...
Australia          NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Austria            NaN    NaN  ...       NaN    NaN    NaN    3.0  NaN
Bahrain            NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Belgium            NaN    NaN  ...       NaN    NaN    NaN   21.0  NaN
Channel Islands    NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Cyprus             NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Denmark            NaN    NaN  ...       NaN    NaN    NaN    8.0  NaN
EIRE              16.0    NaN  ...       NaN    NaN    NaN    NaN  NaN
Finland            NaN    NaN  ...       NaN    NaN    NaN    9.0  NaN
France             NaN    NaN  ...       NaN    NaN    NaN  136.0  NaN
Germany            NaN    NaN  ...       NaN    NaN    NaN  198.0  NaN
Greece             NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Hong Kong          NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Iceland            NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Israel             NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Italy              NaN    NaN  ...       NaN    NaN    NaN   17.0  NaN
Japan              NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Lebanon            NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Lithuania          NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Netherlands        NaN    NaN  ...       NaN    NaN    NaN    3.0  NaN
Norway             NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Poland             NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Portugal          16.0    NaN  ...       NaN    NaN    NaN   41.0  NaN
Singapore          NaN    NaN  ...       NaN    NaN    NaN    NaN  NaN
Spain              NaN    NaN  ...       NaN    NaN   -2.0   19.0  NaN
Sweden             NaN    NaN  ...       NaN    NaN    NaN    4.0  NaN
Switzerland        NaN    NaN  ...       NaN    NaN    NaN    7.0  NaN
United Kingdom    74.0  222.0  ...       3.0  114.0  188.0  993.0 -2.0

StockCode        gift_0001_20  gift_0001_30  gift_0001_40  gift_0001_50    m
Country
Australia                 NaN           NaN           NaN           NaN  NaN
Austria                   NaN           NaN           NaN           NaN  NaN
Bahrain                   NaN           NaN           NaN           NaN  NaN
Belgium                   NaN           NaN           NaN           NaN  NaN
Channel Islands           NaN           NaN           NaN           NaN  NaN
Cyprus                    NaN           NaN           NaN           NaN  NaN
Denmark                   NaN           NaN           NaN           NaN  NaN
EIRE                      NaN           NaN           NaN           NaN  NaN
Finland                   NaN           NaN           NaN           NaN  NaN
France                    NaN           NaN           NaN           NaN  NaN
Germany                   NaN           NaN           NaN           NaN  NaN
Greece                    NaN           NaN           NaN           NaN  NaN
Hong Kong                 NaN           NaN           NaN           NaN  NaN
Iceland                   NaN           NaN           NaN           NaN  NaN
Israel                    NaN           NaN           NaN           NaN  NaN
Italy                     NaN           NaN           NaN           NaN  NaN
Japan                     NaN           NaN           NaN           NaN  NaN
Lebanon                   NaN           NaN           NaN           NaN  NaN
Lithuania                 NaN           NaN           NaN           NaN  NaN
Netherlands               NaN           NaN           NaN           NaN  NaN
Norway                    NaN           NaN           NaN           NaN  NaN
Poland                    NaN           NaN           NaN           NaN  NaN
Portugal                  NaN           NaN           NaN           NaN  NaN
Singapore                 NaN           NaN           NaN           NaN  NaN
Spain                     NaN           NaN           NaN           NaN  NaN
Sweden                    NaN           NaN           NaN           NaN  NaN
Switzerland               NaN           NaN           NaN           NaN  NaN
United Kingdom            2.0           1.0           1.0           1.0  1.0

[28 rows x 3051 columns]

## Fusión de DataFrames en Pandas

In [ ]:
# Ejercicios con merge()
df1 = pd.DataFrame({
  'key': ['A', 'B', 'C'],
  'value1': [1,2,3]
})

df2 = pd.DataFrame({
  'key': ['B', 'C', 'D'],
  'value2': [4,5,6]
})

# Ejercicios con concat()
df3 = pd.DataFrame({
  'A': ['A0', 'A1', 'A2'],
  'B': ['B0', 'B1', 'B2'],
})

df4 = pd.DataFrame({
  'A': ['A3', 'A4', 'A5'],
  'B': ['B3', 'B4', 'B5'],
})

# Ejercicios con join()
df5 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
  },
  index = ['K0', 'K1', 'K2']
)

df6 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['DO', 'D1', 'D2']
  },
  index = ['K0', 'K2', 'K3']
)

print(df1)
print(df2)
print(df3)
print(df4)
print(df5)
print(df6)

  key  value1
0   A       1
1   B       2
2   C       3
  key  value2
0   B       4
1   C       5
2   D       6
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
    A   B
0  A3  B3
1  A4  B4
2  A5  B5
     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  DO
K2  C1  D1
K3  C2  D2

In [ ]:
inner_merged = pd.merge(df1, df2, on='key', how='inner')
print(inner_merged)

  key  value1  value2
0   B       2       4
1   C       3       5

In [ ]:
outer_merged = pd.merge(df1, df2, on='key', how='outer')
print(outer_merged)

  key  value1  value2
0   A     1.0     NaN
1   B     2.0     4.0
2   C     3.0     5.0
3   D     NaN     6.0

coincidencias con el lado del la **izquierda**

In [ ]:
left_merged = pd.merge(df1, df2, on='key', how='left')
print(left_merged)

  key  value1  value2
0   A       1     NaN
1   B       2     4.0
2   C       3     5.0

coinciadencias con el lado del la **derecha**

In [ ]:
left_merged = pd.merge(df1, df2, on='key', how='right')
print(left_merged)

  key  value1  value2
0   B     2.0       4
1   C     3.0       5
2   D     NaN       6

Concatenacion

In [ ]:
vertical_concat = pd.concat([df3, df4], axis=0)
print(vertical_concat)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

In [ ]:
horizontal_concat = pd.concat([df3, df4], axis=1)
print(horizontal_concat)

    A   B   A   B
0  A0  B0  A3  B3
1  A1  B1  A4  B4
2  A2  B2  A5  B5

In [ ]:
print(df5)
print(df6)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  DO
K2  C1  D1
K3  C2  D2

In [ ]:
joined = df5.join(df6, how='inner')
print(joined)

     A   B   C   D
K0  A0  B0  C0  DO
K2  A2  B2  C1  D1

In [ ]:
retail_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
retail_data.dropna(subset=['InvoiceDate'], inplace=True)

In [8]:
retail_data.set_index('InvoiceDate', inplace=True)

In [9]:
retail_data['Year'] = retail_data.index.year
retail_data['Month'] = retail_data.index.month
retail_data['Day'] = retail_data.index.day
retail_data['Weekdy'] = retail_data.index.weekday
retail_data['Hour'] = retail_data.index.hour

print(retail_data['Month'])
print(retail_data['Day'])
print(retail_data['Weekdy'])
print(retail_data['Hour'])

InvoiceDate
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
2010-12-01 08:26:00    12
                       ..
2010-12-06 14:36:00    12
2010-12-06 14:36:00    12
2010-12-06 14:36:00    12
2010-12-06 14:36:00    12
2010-12-06 14:36:00    12
Name: Month, Length: 12913, dtype: int32
InvoiceDate
2010-12-01 08:26:00    1
2010-12-01 08:26:00    1
2010-12-01 08:26:00    1
2010-12-01 08:26:00    1
2010-12-01 08:26:00    1
                      ..
2010-12-06 14:36:00    6
2010-12-06 14:36:00    6
2010-12-06 14:36:00    6
2010-12-06 14:36:00    6
2010-12-06 14:36:00    6
Name: Day, Length: 12913, dtype: int32
InvoiceDate
2010-12-01 08:26:00    2
2010-12-01 08:26:00    2
2010-12-01 08:26:00    2
2010-12-01 08:26:00    2
2010-12-01 08:26:00    2
                      ..
2010-12-06 14:36:00    0
2010-12-06 14:36:00    0
2010-12-06 14:36:00    0
2010-12-06 14:36:00    0
2010-12-06 14:36:00    0
Name: Weekdy, Length: 12913, dtype: int32
InvoiceDate
2010-12-01 08:26:00     8
2010-12-01 08:26:00     8
2010-12-01 08:26:00     8
2010-12-01 08:26:00     8
2010-12-01 08:26:00     8
                       ..
2010-12-06 14:36:00    14
2010-12-06 14:36:00    14
2010-12-06 14:36:00    14
2010-12-06 14:36:00    14
2010-12-06 14:36:00    14
Name: Hour, Length: 12913, dtype: int32

In [10]:
retail_data

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Weekdy,Hour
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,2,8
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-06 14:36:00,537400,22659,LUNCH BOX I LOVE LONDON,2.0,1.95,17191.0,United Kingdom,2010,12,6,0,14
2010-12-06 14:36:00,537400,22429,ENAMEL MEASURING JUG CREAM,3.0,4.25,17191.0,United Kingdom,2010,12,6,0,14
2010-12-06 14:36:00,537400,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12.0,1.25,17191.0,United Kingdom,2010,12,6,0,14
2010-12-06 14:36:00,537400,22758,LARGE PURPLE BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,0,14
2010-12-06 14:36:00,537400,22756,LARGE YELLOW BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,0,14

In [11]:
retail_data = retail_data.drop(columns=['Weekdy'])

In [12]:
retail_data

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Hour
InvoiceDate,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,8
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,8
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,8
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,8
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,8
...,...,...,...,...,...,...,...,...,...,...,...
2010-12-06 14:36:00,537400,22659,LUNCH BOX I LOVE LONDON,2.0,1.95,17191.0,United Kingdom,2010,12,6,14
2010-12-06 14:36:00,537400,22429,ENAMEL MEASURING JUG CREAM,3.0,4.25,17191.0,United Kingdom,2010,12,6,14
2010-12-06 14:36:00,537400,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12.0,1.25,17191.0,United Kingdom,2010,12,6,14
2010-12-06 14:36:00,537400,22758,LARGE PURPLE BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14
2010-12-06 14:36:00,537400,22756,LARGE YELLOW BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14

In [13]:
retail_data['Weekdy'] = retail_data.index.weekday

In [14]:
retail_data

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Hour,Weekdy
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-06 14:36:00,537400,22659,LUNCH BOX I LOVE LONDON,2.0,1.95,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22429,ENAMEL MEASURING JUG CREAM,3.0,4.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22758,LARGE PURPLE BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22756,LARGE YELLOW BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0

In [20]:
retail_data_2010 = retail_data.loc['2010']
retail_data_2010

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Hour,Weekdy
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-06 14:36:00,537400,22659,LUNCH BOX I LOVE LONDON,2.0,1.95,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22429,ENAMEL MEASURING JUG CREAM,3.0,4.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22758,LARGE PURPLE BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22756,LARGE YELLOW BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0

In [21]:
retail_data_2010_12 = retail_data.loc['2010-12']
retail_data_2010_12

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Hour,Weekdy
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
...,...,...,...,...,...,...,...,...,...,...,...,...
2010-12-06 14:36:00,537400,22659,LUNCH BOX I LOVE LONDON,2.0,1.95,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22429,ENAMEL MEASURING JUG CREAM,3.0,4.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22771,CLEAR DRAWER KNOB ACRYLIC EDWARDIAN,12.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22758,LARGE PURPLE BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0
2010-12-06 14:36:00,537400,22756,LARGE YELLOW BABUSHKA NOTEBOOK,2.0,1.25,17191.0,United Kingdom,2010,12,6,14,0

Rangos de fechas

In [24]:
df_range_range = retail_data.loc['2010-12-01':'2010-12-14']
df_range_range.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country,Year,Month,Day,Hour,Weekdy
InvoiceDate,,,,,,,,,,,,
2010-12-01 08:26:00,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,2.55,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,71053,WHITE METAL LANTERN,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,2.75,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2
2010-12-01 08:26:00,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,3.39,17850.0,United Kingdom,2010,12,1,8,2

In [30]:
df_range = pd.date_range(start='2010-12-01', end='2010-12-14', freq='D')

df_range

DatetimeIndex(['2010-12-01', '2010-12-02', '2010-12-03', '2010-12-04',
               '2010-12-05', '2010-12-06', '2010-12-07', '2010-12-08',
               '2010-12-09', '2010-12-10', '2010-12-11', '2010-12-12',
               '2010-12-13', '2010-12-14'],
              dtype='datetime64[ns]', freq='D')

Guardar las fechas dentro de la la columna Date, de nuevo rango creado utilizando el date_range de pandas

In [31]:
da_date = pd.DataFrame(df_range, columns=['Date'])
da_date.head()

        Date
0 2010-12-01
1 2010-12-02
2 2010-12-03
3 2010-12-04
4 2010-12-05